name: CI
on:
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    ci:
        name: Building, linting, testing on node ${{ matrix.node }} and ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node: ['20.x']
                os: [ubuntu-latest]
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3  # Update to v3

            - name: Use Node ${{ matrix.node }}
              uses: actions/setup-node@v3  # Update to v3
              with:
                  node-version: ${{ matrix.node }}

            # Optionally, use the latest npm version if appropriate
            - name: Setup latest npm version
              run: npm install -g npm@latest  # Ensure you need this specific npm version
            
            - name: Install project dependencies
              run: npm instal

            - name: Install deps and build (with cache)
              uses: bahmutov/npm-install@v1

            - name: Lint
              run: npm run lint

            - name: Test
              run: npm test -- --ci --coverage --maxWorkers=2

            - name: Build
              run: npm run build
